/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446.h"
#include"stm32_gpio_driver.h"

int main(void)
{
    GPIO_Handle_t Led_control;
    Led_control.pGPIOx = GPIOA;
    Led_control.PinConfig.mode =OUTPUT;
    Led_control.PinConfig.pin=GPIO_PIN_5;
    Led_control.PinConfig.speed=HIGH_SPEED;
    Led_control.PinConfig.PinopType=PUSH_PULL;
    Led_control.PinConfig.pupdControl=NO_PULL_UP_PULL_DOWN;

    GPIO_Init(&Led_control);

    while(1)
    {

    	GPIO_Toggle(Led_control.pGPIOx,GPIO_PIN_5);
    	for(int i = 0; i<10000000;i++);

    }

}
